import { StyleSheet } from 'react-native';
import { C } from '../styles/colors';

export const styles = StyleSheet.create({
  headerContainer: {
    backgroundColor: C.card,
    borderBottomColor: C.border,
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 35,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerLeft: {
    flex: 1,
    minWidth: 0,
  },
  hamburger: {
    padding: 6,
    marginRight: -6,
  },
  hamburgerText: {
    fontSize: 24,
    color: C.t1,
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: C.t1,
    letterSpacing: -0.3,
  },
  headerSub: {
    fontSize: 12,
    color: C.t3,
    marginTop: 2,
    lineHeight: 15,
  },
  headerBtn: {
    backgroundColor: '#38bdf8',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    minWidth: 'auto',
  },
  headerBtnTxt: {
    color: '#0a0f1a',
    fontWeight: '800',
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  searchBar: {
    padding: 8,
    paddingBottom: 6,
    backgroundColor: C.card,
  },
  bar: {
    flexDirection: 'row',
    gap: 10,
    padding: 8,
    paddingBottom: 6,
    backgroundColor: C.card,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.el,
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  searchIcon: {
    fontSize: 16,
    marginRight: 8,
    color: C.t3,
  },
  searchInput: {
    flex: 1,
    color: C.t1,
    fontSize: 14,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  clearBtn: {
    padding: 6,
    marginLeft: 4,
  },
  clearBtnText: {
    fontSize: 16,
    color: C.t2,
    fontWeight: '700',
  },
  list: {
    padding: 8,
    paddingTop: 6,
  },
  countContainer: {
    paddingHorizontal: 4,
    paddingVertical: 6,
    marginBottom: 4,
  },
  countText: {
    fontSize: 12,
    color: C.t2,
    fontWeight: '500',
  },
  card: {
    backgroundColor: C.card,
    borderRadius: 12,
    padding: 13,
    marginBottom: 9,
    borderWidth: 1,
    borderColor: C.border,
  },
  top: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 9,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarTxt: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  name: {
    fontSize: 13,
    fontWeight: '700',
    color: C.t1,
  },
  email: {
    fontSize: 10,
    color: C.t3,
    marginTop: 2,
    fontFamily: 'monospace',
  },
  iBtn: {
    padding: 5,
  },
  meta: {
    flexDirection: 'row',
    gap: 7,
    marginBottom: 7,
  },
  lastLogin: {
    fontSize: 10,
    color: C.t3,
    fontStyle: 'italic',
  },
  errBox: {
    backgroundColor: C.red + '22',
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: C.red + '44',
  },
  errTxt: {
    color: C.red,
    fontSize: 12,
    fontWeight: '600',
  },
});